### ISSUE TITLE
Improve type inference for (.==), (.>=), ...

### ISSUE THREAD

**Issue by i-am-tom** [i-am-tom/holmes#10]
In order to produce `lift`, the following class was created:

```
class Lifting (f :: Type -> Type) (c :: Type -> Constraint) | f -> c where
  lift' :: c x => x -> f x
```

Now, if we say `lift 3 .== lift 4 :: Prop m (Defined Bool)`, we run into a problem: we can't infer a type of `Defined Int` (specifically the `Defined` part) for the `3` and `4`, because there's no reversing functional dependency on the `EqR` class to get us from `Defined Bool` back to `Defined Int`. This makes sense - the instances are of the shape `EqR (Defined x) (Defined Bool)`, so you couldn't have a functional dependency in the other direction even if you wanted one.

The type inference could be fixed if we restructured the `EqR` and `OrdR` classes to be of the same shape:

```
class EqR (f :: Type -> Type) (c :: Type -> Constraint) | f -> c where
  eqR :: c x => (f x, f x, f Bool) -> (f x, f x, f Bool)
```

Now, we've guaranteed that the parameter type of the input and bool result match. This means that with `lift 3 .== lift 4 :: Prop m (Defined Bool)`, it is clear that the type of `3` must be `(Num x => Defined x)`, which is what we're after.

This is not a lot of work, but it might be a good first issue if someone fancies getting involved in the library!

**Comment by robx** [comment]
I'd be happy to give this one a try! Seems like a good exercise in some of the (too me) higher GHC type magic.

**Comment by robx** [comment]
So, I ran into some trouble with my first attempt:

With `class EqR` as suggested

```
class EqR (f :: Type -> Type) (c :: Type -> Constraint) | f -> c where
  eqR :: c x => ( f x, f x, f Bool ) -> ( f x, f x, f Bool )
```

I can provide an instance for `Defined`:

```
instance EqR Defined Eq where
   ...
```

but am not sure it's possible / can't figure out how to provide an instance for `Intersect`. I think I want something like

```
instance EqR Intersect (\ x -> (Bounded x, Enum x, Ord x, Hashable x)) where
```

but my best attempt, a type alias

```
type IntersectEqConstraint x = (Bounded x, Enum x, Ord x, Hashable x)

instance EqR Intersect IntersectEqConstraint where
```

fails:

```
    • The type synonym ‘IntersectEqConstraint’ should have 1 argument, but has been given none
    • In the instance declaration for
        ‘EqR Intersect IntersectEqConstraint’
```

My understanding is that I *need* the constraint to be a proper class of its own and not just an alias in order to use it in an instance declaration like this, and it seems maybe not possible to do that while keeping this definition of `EqR`. Do you see a way to provide an `Intersect` instance for this `EqR`?

(One approach might be to go through a newtype wrapper

```
newtype Intersectable x = Intersectable x

class IntersectEqConstraint (x :: Type)
instance (Bounded x, Enum x, Ord x, Hashable x) => IntersectEqConstraint (Intersectable x)
```

and modify `EqR` to something like `eqR :: c (wrapper x) => ...` but that seems messy.)

I did find a slightly different solution using type families though:

```
type family EqConstraint (f :: Type -> Type) x :: Constraint

class EqR (f :: Type -> Type) where
  eqR :: EqConstraint f x => ( f x, f x, f Bool ) -> ( f x, f x, f Bool )

type instance EqConstraint Defined x = Eq x
type instance EqConstraint Intersect x = (Bounded x, Enum x, Ord x, Hashable x)
```

Would this approach make sense to you?

**Comment by robx** [comment]
(I have no idea whether the type family solution provides the desired type inference benefits...)

**Comment by i-am-tom** [comment]
Look up Intersectable in the Data.JoinSemilattice.Intersect module :)

This is a useful trick to know - because type families are unmatchable (*cough* @kcsongor *cough*), you can create "constraint aliases" like this:

```
class (A x, B x, C x) => D x
instance (A x, B x, C x) => D x
```

The first line means, "any instance of D definitely has an instance of A/B/C". The second means, "anything has an instance of D if it has an instance of A/B/C". Effectively, D is now a synonym for A/B/C. :)

**Comment by robx** [comment]
Ah, neat! I'd tried it without the constraint on the `class` declaration, but then you need `UndecidableInstances` and everything seems to break down.
