### ISSUE TITLE
stack overflow / infinite loop when solving with Intersect instead of Defined

### ISSUE THREAD

**Issue by robx** [i-am-tom/holmes#7]
Chances are I'm doing something wrong here, but since I'm at a point where I'm likely to shelve this toy project, thought I should report my problem just in case it's an issue with Holmes.

Concretely, my puzzle solver runs fine and slow with `Defined`, and typechecks but doesn't run at all with `Intersect`. (Doesn't run at all means: stack overflow in GHCI, non-termination in compiled executable.)

The offending function seems to be:

```
-- given a list of values at indexes, count how many of these occur
countEqual ::
  (Eq x, Mapping f c, c x, c v, Num v, Num (f v), SumR (f v), MonadCell m) =>
  [(Int, x)] ->
  [Prop m (f x)] ->
  Prop m (f v)
countEqual vals cells = foldr (.+) (lift 0) (map f vals)
  where
    isEqual v w = if w == v then 1 else 0
    f (i, v) = isEqual v .$ (cells !! i)
```

With this (and a bounded integer type [Val4](https://github.com/robx/puzzles/blob/eb45c93d5df0126c5b4a15e5c70aac6e165fa057/towerdefence/src/TowerIntersect.hs#L22) with range 0..4), I see:

```
> let cfg = 1 `from` [1] :: Config Holmes (Defined Int)
> let prop = (\cells -> countEqual [(0, 3::Int)] cells .>= lift (pure (0::Int))) :: MonadCell m => [ Prop m (Defined Int)] -> Prop m (Defined Bool)
> cfg `satisfying` prop
Just [Exactly 1]
> let cfg = 1 `from` [1] :: Config Holmes (Intersect Val4)
> let prop cells = countEqual [(0, 3::Val4)] cells .>= lift (singleton (0::Val4))
> cfg `satisfying` prop
*** Exception: stack overflow
```

(Chances are there's a better way to do what I'm doing. The thing I'm trying to encode is that some values on a Sudoku-like board count certain other cells in the board according to their values and relative position.)

Thanks for making Holmes by the way! Certainly had fun figuring things out this far.

**Comment by i-am-tom** [comment]
Interesting - I _think_ the problem is that your count is producing an `Intersect Int` for the result type (the `Prop m (f v)` in your countEqual presumably monomorphises to `Prop Holmes (Intersect Int)`), which means that, in order to execute the query, Holmes has to produce a `mempty` to fill in with propagated information. This means creating an `Intersect` of all `Int` values, which is leading to... well, a very long process!

**Comment by i-am-tom** [comment]
Easiest way to fix this would be to produce a `Prop m (Defined Int)` result, rather than something `f`-polymorphic, but I'll have a think in case there's a neater way to embed this functionality in the library...

**Comment by robx** [comment]
I don't think that's it, at least I don't see how anything would monomorphize to `Int` in the example. The sum should be explicitly typed as `Intersect Val4`.

I get the same hang with

```
countEqualMono ::
  MonadCell m =>
  [(Int, Val4)] ->
  [Prop m (Intersect Val4)] ->
  Prop m (Intersect Val4)
countEqualMono vals cells = foldr (.+) (lift 0) (map f vals)
  where
    isEqual v w = if w == v then 1 else 0
    f (i, v) = isEqual v .$ (cells !! i)
```

Compare https://github.com/robx/puzzles/commit/922cb82d129cc54b82e4053f8751a3be6cdc13f2.

**Comment by i-am-tom** [comment]
Going to close this as I think #12 will give you an approach that should fix this problem :)

**Comment by robx** [comment]
I don't really see how #12 helps...  This report probably lacked enough context, but I need to compare `countEqual` to a `Prop m (Defined Int)`, not to a constant `Int`. The [function](https://github.com/robx/puzzles/blob/eb45c93d5df0126c5b4a15e5c70aac6e165fa057/towerdefence/src/Tower.hs#L145) is

```
towerConstraint board coord cells = eq .>= toNum (cells !! toIndex board coord)
  where
    as = attackers board coord
    eq = countEqual [(toIndex board c, v) | (c, v) <- as] cells
```

I get that I could generalize this new `exactly` to `atLeast` in some way,  but isn't it a crucial difference that I'm comparing to a non-constant? I.e., I believe what I'd need would be something like:

```
exactly :: (BooleanR f, MonadCell m) => Prop m (f Int) -> (x -> Prop m (f Bool)) -> [x] -> Prop m (f Bool)
```

(Apart from that, I'm curious whether the solver looping is generally a possibility when working with such constraint solvers.)

**Comment by i-am-tom** [comment]
I've been on a bit of an adventure this week, but I think I've finally reached the answer. What happened here was we hit on two separate pieces of bad luck. Defining `Val4` solved the first of the two:

```haskell
newtype Val4 = V4 Int
  deriving stock (Show, Eq, Ord, Generic)
  deriving anyclass (Hashable)

instance Num Val4 where
  fromInteger = toEnum . fromInteger

  (V4 a) + (V4 b) = if a + b > 4 then V4 4 else V4 (a + b)
```

The _second_ part is how this addition gets lifted into propagator networks. Specifically, the two-argument function becomes a three-variable **relationship**:

```haskell
class Merge x => SumR (x :: Type) where
  addR :: ( x, x, x ) -> ( x, x, x )

  default addR :: Num x => ( x, x, x ) -> ( x, x, x )
  addR ( x, y, z ) = ( z - y, z - x, x + y )
```

Subtraction! We didn't define subtraction for `Val4`, though, so GHC uses its default implementations:

```haskell
    x - y               = x + negate y
    negate x            = 0 - x
```

... which means that `z - y` will always result in an infinite loop 😅

The solution? Just define subtraction:

```haskell
instance Num Val4 where
  fromInteger = toEnum . fromInteger

  V4 a + V4 b = if a + b > 4 then V4 4 else V4 (a + b)
  V4 a - V4 b = if a - b < 0 then V4 0 else V4 (a - b) -- Eureka!
```

I'm sorry it took so long to get this one worked out (nearly a month!); I really was stumped for a while.

I've added this example as [a regression test](https://github.com/i-am-tom/holmes/blob/master/test/Test/Regression/Issue7.hs) (despite it not being a regression in the end), because I think this is a useful reference for when it inevitably happens again. I hope that's OK with you - happy to remove it if not :)
